interface BodyBoleto {
    pagadorDocumentoTipo: number;
    pagadorDocumentoNumero: string;
    pagadorNome: string;
    pagadorEndereco: string;
    pagadorBairro: string;
    pagadorCidade: string;
    pagadorUf: string;
    pagadorCep: string;
    dataVencimento: string;
    valorNominal: number;
    multaPercentual: number;
    multaQuantidadeDias: number;
    jurosPercentual: number;
    tipoDesconto: number;
    descontoValor: number;
    descontoDataLimite: string;
    valorAbatimento: number;
    tipoProtesto: number;
    protestoQuantidadeDias: number;
    baixaQuantidadeDias: number;
    mensagem: string;
    tipoTitulo: number;
    seuNumero: number;
    pagadorEmail: string;
    emailEnvio: boolean;
    emailAssunto: string;
    emailConteudo: string;
    pagadorCelular: string;
    smsEnvio: boolean;
    nossoNumero: string;
    convenioId: string;
    incluirPix: boolean
  }