name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: yarn list

      - name: Build artifacts
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install --non-interactive
      - run: node ace build --production --ignore-ts-errors
      - run: |
          cd build
          yarn install --production --non-interactive
          tar cf ${GITHUB_REF##*/}.tar .

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-folder
          path: |
            build/${GITHUB_REF##*/}.tar
            .env*
          retention-days: 5

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: build-folder

      - name: Display structure of downloaded files
        run: ls -lhart
        working-directory: api/